config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  
  get 'about'=> 'static_pages#about'
  
  get 'contact' => 'static_pages/contact'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="http://www.michaelhart1.com/">Michael Hart1</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact",contact_path %></li>
            <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Week6app", root_path,id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to "Home", root_path %></li>
        <li><%=link_to "Help", help_path %></li>
        <li><%=link_to "Log in", '#' %></li>
        
      </ul>
    </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<%= render 'layouts/shim'%>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>
  

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    
<head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<h1>MY APPP</h1>
<p>THIS IS MY ABOUT PAGE</p>

<%= link_to 'home', root_path %>
<%= link_to 'help', help_path %>
<%= link_to 'contact', contact_path %> 


xxx

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
    
<head>
   <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<h1>MY APP</h1>
<p>THIS IS A CONTACT PAGE</p>

<%= link_to 'home', root_path %>
<%= link_to 'about', about_path %>
<%= link_to 'help', help_path %>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

    
<head>
   <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<h1>MY APP</h1>
<p>THIS IS HELP PAGE</p>

<%= link_to 'home', root_path %>
<%= link_to 'about', about_path %>
<%= link_to 'contact', contact_path %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

    
<head>
  <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<div class="center jumbotron"><center>
<h1>Welcome to my app page</h1>
<p>MAIN PAGE</p>
<h3>This is my ruby website app that im working on in griffith college</h3>

<%=link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %><br>
</div></center>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
'http://rubyonrails.org/' %>